spring.application.name=PC1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.docker.compose.lifecycle-management=start-only
jwt.secret=asffkljlsajflksjflsjgldsjlkgjsldgjsgslldjfsljgls
jwt.expiration=3600000